In [17]:
import numpy as np
import pandas as pd
import seaborn as sns

In [18]:
df=sns.load_dataset('iris')

In [19]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
df.groupby('species').size()

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X=df.drop('species' , axis=1)

In [23]:
y=df['species']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.33, random_state=42)

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
model_KNN=KNeighborsClassifier(n_neighbors=11)

In [27]:
model_KNN.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=11)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [29]:
y_knn=model_KNN.predict(X_test)

In [32]:
accuracy_score(y_test , y_knn)  #Testing accuracy

1.0

In [34]:
from sklearn.svm import SVC

In [43]:
model_SVM=SVC(C=10 , gamma='auto' , kernel='linear')

In [44]:
model_SVM.fit(X_train , y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [45]:
y_svm=model_SVM.predict(X_test)

In [46]:
accuracy_score(y_test , y_svm)

1.0

In [47]:
### IMPLEMENTING GRID SEARCH CV

In [48]:
from sklearn.model_selection import GridSearchCV

In [49]:
model_SVM2=SVC(gamma='auto') # for gscv , just model should exist , not trained.

In [50]:
classifier=GridSearchCV((model_SVM2) ,
                        {
                            'C' : [1,10,20,30],
                            'kernel' : ['rbf' , 'linear']
                        },
                        cv=5,
                        return_train_score=False
                        )

In [51]:
classifier.fit(X,y) # In Cross validation(CV) , only Real x and y are passed( not the train test spit one.)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [52]:
classifier.cv_results_

{'mean_fit_time': array([0.01298285, 0.01766915, 0.01468801, 0.01381865, 0.01093903,
        0.00702419, 0.00546865, 0.00309854]),
 'std_fit_time': array([0.00268863, 0.00579041, 0.00274464, 0.00454113, 0.00364696,
        0.0021388 , 0.00184205, 0.00011725]),
 'mean_score_time': array([0.00920625, 0.01184802, 0.01232247, 0.01012583, 0.01128802,
        0.00579114, 0.00323849, 0.00310264]),
 'std_score_time': array([0.00321145, 0.00354876, 0.00407049, 0.00259461, 0.0016551 ,
        0.00148635, 0.00099712, 0.00153013]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [53]:
results=pd.DataFrame(classifier.cv_results_)

In [54]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012983,0.002689,0.009206,0.003211,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.017669,0.005790,0.011848,0.003549,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.014688,0.002745,0.012322,0.004070,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.013819,0.004541,0.010126,0.002595,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.010939,0.003647,0.011288,0.001655,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.007024,0.002139,0.005791,0.001486,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.005469,0.001842,0.003238,0.000997,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003099,0.000117,0.003103,0.001530,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [58]:
results[['param_C' , 'param_kernel' , 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [60]:
print(classifier.best_params_)

{'C': 1, 'kernel': 'rbf'}

In [62]:
print(classifier.best_score_)

0.9800000000000001