In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df=sns.load_dataset('iris')

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df.groupby('species').size()

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X=df.drop('species' , axis=1)

In [9]:
y=df['species']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_KNN=KNeighborsClassifier(n_neighbors=11)

In [13]:
model_KNN.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=11)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
y_knn=model_KNN.predict(X_test)

In [16]:
accuracy_score(y_test , y_knn)  #Testing accuracy

1.0

In [17]:
from sklearn.svm import SVC

In [18]:
model_SVM=SVC(C=10 , gamma='auto' , kernel='linear')

In [19]:
model_SVM.fit(X_train , y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [20]:
y_svm=model_SVM.predict(X_test)

In [21]:
accuracy_score(y_test , y_svm)

1.0

In [22]:
### IMPLEMENTING GRID SEARCH CV

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
model_SVM2=SVC(gamma='auto') # for gscv , just model should exist , not trained.

In [25]:
classifier=GridSearchCV((model_SVM2) ,
                        {
                            'C' : [1,10,20,30],
                            'kernel' : ['rbf' , 'linear']
                        },
                        cv=5,
                        return_train_score=False
                        )

In [26]:
classifier.fit(X,y) # In Cross validation(CV) , only Real x and y are passed( not the train test spit one.)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [27]:
classifier.cv_results_

{'mean_fit_time': array([0.00286512, 0.00259132, 0.002736  , 0.00244074, 0.00245142,
        0.00240951, 0.00256371, 0.00255971]),
 'std_fit_time': array([3.67079991e-04, 2.97296760e-04, 1.63804953e-04, 1.72463134e-04,
        3.76806969e-05, 1.14737999e-04, 2.94641573e-04, 3.78438992e-04]),
 'mean_score_time': array([0.00210075, 0.00182781, 0.00205097, 0.00182858, 0.00179596,
        0.00182796, 0.00176582, 0.00182557]),
 'std_score_time': array([3.39774646e-04, 5.17133361e-05, 2.05214482e-04, 6.43559893e-05,
        1.46128612e-05, 1.02307965e-04, 4.42769941e-05, 1.13210521e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [28]:
results=pd.DataFrame(classifier.cv_results_)

In [29]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002865,0.000367,0.002101,0.000340,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002591,0.000297,0.001828,0.000052,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002736,0.000164,0.002051,0.000205,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002441,0.000172,0.001829,0.000064,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002451,0.000038,0.001796,0.000015,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002410,0.000115,0.001828,0.000102,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002564,0.000295,0.001766,0.000044,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002560,0.000378,0.001826,0.000113,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [30]:
results[['param_C' , 'param_kernel' , 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [31]:
print(classifier.best_params_)

{'C': 1, 'kernel': 'rbf'}

In [32]:
print(classifier.best_score_)

0.9800000000000001

In [33]:
from sklearn.model_selection import RandomizedSearchCV

In [34]:
classifier2=RandomizedSearchCV((model_SVM2) ,
                        {
                            'C' : [1,10,20,30],
                            'kernel' : ['rbf' , 'linear']
                        },
                        n_iter=2,
                        cv=5,
                        return_train_score=False
                        )

In [35]:
classifier2.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [37]:
results2=pd.DataFrame(classifier2.cv_results_)

In [43]:
results2[['param_C' , 'param_kernel' , 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       30          rbf         0.960000
1       20       linear         0.966667

In [45]:
print(classifier2.best_params_)

{'kernel': 'linear', 'C': 20}

In [46]:
print(classifier2.best_score_)

0.9666666666666666